services:
  account-service:
    build:
      context: ./services/account
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./services/account/.env
    depends_on:
      postgres-account:
        condition: service_healthy
    networks:
      - postgres

  postgres-account:
    image: postgres:17
    container_name: postgres-account
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-nerdland}
      PGDATA: /data/postgres
    volumes:
      - postgres-account:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-nerdland}"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-tweets:
    image: postgres:17
    container_name:  postgres-tweets
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-nerdland}
      PGDATA: /data/postgres
    volumes:
      - postgres-tweets:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-nerdland}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres-account:
  postgres-tweets:
  pgadmin: