// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/api/tweets/tweets.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTweetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTweetRequest) Reset() {
	*x = CreateTweetRequest{}
	mi := &file_internal_api_tweets_tweets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetRequest) ProtoMessage() {}

func (x *CreateTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_tweets_tweets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetRequest.ProtoReflect.Descriptor instead.
func (*CreateTweetRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_tweets_tweets_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTweetRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateTweetRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TweetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TweetResponse) Reset() {
	*x = TweetResponse{}
	mi := &file_internal_api_tweets_tweets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TweetResponse) ProtoMessage() {}

func (x *TweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_tweets_tweets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TweetResponse.ProtoReflect.Descriptor instead.
func (*TweetResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_tweets_tweets_proto_rawDescGZIP(), []int{1}
}

func (x *TweetResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TweetResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *TweetResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_internal_api_tweets_tweets_proto protoreflect.FileDescriptor

const file_internal_api_tweets_tweets_proto_rawDesc = "" +
	"\n" +
	" internal/api/tweets/tweets.proto\x12\x06tweets\"G\n" +
	"\x12CreateTweetRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"R\n" +
	"\rTweetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text2P\n" +
	"\fTweetService\x12@\n" +
	"\vCreateTweet\x12\x1a.tweets.CreateTweetRequest\x1a\x15.tweets.TweetResponseB\x1fZ\x1dtweets/internal/api/tweets;pbb\x06proto3"

var (
	file_internal_api_tweets_tweets_proto_rawDescOnce sync.Once
	file_internal_api_tweets_tweets_proto_rawDescData []byte
)

func file_internal_api_tweets_tweets_proto_rawDescGZIP() []byte {
	file_internal_api_tweets_tweets_proto_rawDescOnce.Do(func() {
		file_internal_api_tweets_tweets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_tweets_tweets_proto_rawDesc), len(file_internal_api_tweets_tweets_proto_rawDesc)))
	})
	return file_internal_api_tweets_tweets_proto_rawDescData
}

var file_internal_api_tweets_tweets_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_api_tweets_tweets_proto_goTypes = []any{
	(*CreateTweetRequest)(nil), // 0: tweets.CreateTweetRequest
	(*TweetResponse)(nil),      // 1: tweets.TweetResponse
}
var file_internal_api_tweets_tweets_proto_depIdxs = []int32{
	0, // 0: tweets.TweetService.CreateTweet:input_type -> tweets.CreateTweetRequest
	1, // 1: tweets.TweetService.CreateTweet:output_type -> tweets.TweetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_tweets_tweets_proto_init() }
func file_internal_api_tweets_tweets_proto_init() {
	if File_internal_api_tweets_tweets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_tweets_tweets_proto_rawDesc), len(file_internal_api_tweets_tweets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_tweets_tweets_proto_goTypes,
		DependencyIndexes: file_internal_api_tweets_tweets_proto_depIdxs,
		MessageInfos:      file_internal_api_tweets_tweets_proto_msgTypes,
	}.Build()
	File_internal_api_tweets_tweets_proto = out.File
	file_internal_api_tweets_tweets_proto_goTypes = nil
	file_internal_api_tweets_tweets_proto_depIdxs = nil
}
